# Generated by Django 5.2.17 on 2026-09-07 17:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardening', '0001_initial'),
        ('plants', '0002_stockmovement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantcaretask',
            name='description',
        ),
        migrations.AddField(
            model_name='plantcaretask',
            name='skip_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantcaretask',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantcaretask',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Claimed', 'Claimed'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Skipped', 'Skipped')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='plantcaretask',
            name='task_type',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='PlantCareHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_type', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('Completed', 'Completed'), ('Skipped', 'Skipped')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plant_care_history', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_history', to='plants.plant')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_records', to='gardening.plantcaretask')),
            ],
        ),
        migrations.CreateModel(
            name='PlantCareSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_type', models.CharField(choices=[('Watering', 'Watering'), ('Fertilizing', 'Fertilizing'), ('Pruning', 'Pruning'), ('Pest Treatment', 'Pest Treatment'), ('Disease Treatment', 'Disease Treatment'), ('Soil Replacement', 'Soil Replacement'), ('Repotting', 'Repotting'), ('General Care', 'General Care')], max_length=50)),
                ('frequency_days', models.PositiveIntegerField(help_text='Number of days between care activities.')),
                ('next_due_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_schedules', to='plants.plant')),
            ],
        ),
        migrations.AddField(
            model_name='plantcaretask',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='gardening.plantcareschedule'),
        ),
    ]
