# Generated by Django 5.2.17 on 2026-09-15 10:49

import django.db.models.deletion
from django.db import migrations, models


def create_task_types_and_convert_schedules(apps, schema_editor):
    GardeningTaskType = apps.get_model(
        'gardening',
        'GardeningTaskType'
    )
    PlantCareSchedule = apps.get_model(
        'gardening',
        'PlantCareSchedule'
    )

    # Get all existing care types from old schedules
    existing_types = (
        PlantCareSchedule.objects
        .values_list('care_type', flat=True)
        .distinct()
    )

    # Create a GardeningTaskType for each existing type
    task_types = {}

    for care_type in existing_types:
        if care_type:
            task_type, created = GardeningTaskType.objects.get_or_create(
                name=care_type
            )
            task_types[care_type] = task_type.id

    # Convert existing schedule care_type values
    # from text such as "Watering" to the new task type ID
    for care_type, task_type_id in task_types.items():
        PlantCareSchedule.objects.filter(
            care_type=care_type
        ).update(
            care_type=task_type_id
        )


class Migration(migrations.Migration):

    dependencies = [
        ('gardening', '0002_remove_plantcaretask_description_and_more'),
    ]

    operations = [

        migrations.CreateModel(
            name='GardeningTaskType',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                (
                    'name',
                    models.CharField(
                        max_length=100,
                        unique=True
                    )
                ),
                (
                    'description',
                    models.TextField(
                        blank=True,
                        null=True
                    )
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=True
                    )
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True
                    )
                ),
            ],
        ),

        migrations.AlterField(
            model_name='plantcarehistory',
            name='care_type',
            field=models.CharField(
                max_length=100
            ),
        ),

        migrations.AlterField(
            model_name='plantcaretask',
            name='task_type',
            field=models.CharField(
                max_length=100
            ),
        ),

        # Temporarily keep the schedule column as text
        # while we convert existing values.
        migrations.AlterField(
            model_name='plantcareschedule',
            name='care_type',
            field=models.CharField(
                max_length=100
            ),
        ),

        migrations.RunPython(
            create_task_types_and_convert_schedules,
            migrations.RunPython.noop
        ),

        # Now convert the column to the ForeignKey.
        migrations.AlterField(
            model_name='plantcareschedule',
            name='care_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='care_schedules',
                to='gardening.gardeningtasktype'
            ),
        ),
    ]